name: McMmoView
main: cn.handyplus.mcmmo.McMmoView
version: 1.1.1
author: handy
website: https://ricedoc.handyplus.cn/wiki/McMmoView
api-version: 1.13
depend: [ mcMMO ]
softdepend: [ PlaceholderAPI ]
description: mcMMO可视化gui
folia-supported: true
commands:
  mcMmoView:
    description: mcMMO可视化gui
    aliases: [ mmv ]
permissions:
  mcMmoView.*:
    description: mcMMO可视化gui
    children:
      mcMmoView.reload: true
      mcMmoView.open: true
  mcMmoView.reload:
    description: 重新加载配置
    default: op
  mcMmoView.open:
    description: 打开GUI
    default: true